/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AfterSaleInfoBean
 */
export interface AfterSaleInfoBean {
    /**
     * 
     * @type {number}
     * @memberof AfterSaleInfoBean
     */
    afterSaleStatus?: number;
    /**
     * 
     * @type {number}
     * @memberof AfterSaleInfoBean
     */
    afterSaleType?: number;
    /**
     * 
     * @type {number}
     * @memberof AfterSaleInfoBean
     */
    refundStatus?: number;
}

export function AfterSaleInfoBeanFromJSON(json: any): AfterSaleInfoBean {
    return AfterSaleInfoBeanFromJSONTyped(json, false);
}

export function AfterSaleInfoBeanFromJSONTyped(json: any, ignoreDiscriminator: boolean): AfterSaleInfoBean {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'afterSaleStatus': !exists(json, 'after_sale_status') ? undefined : json['after_sale_status'],
        'afterSaleType': !exists(json, 'after_sale_type') ? undefined : json['after_sale_type'],
        'refundStatus': !exists(json, 'refund_status') ? undefined : json['refund_status'],
    };
}

export function AfterSaleInfoBeanToJSON(value?: AfterSaleInfoBean | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'after_sale_status': value.afterSaleStatus,
        'after_sale_type': value.afterSaleType,
        'refund_status': value.refundStatus,
    };
}


