/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface InventoryListBean
 */
export interface InventoryListBean {
    /**
     * 
     * @type {string}
     * @memberof InventoryListBean
     */
    warehouseId?: string;
    /**
     * 
     * @type {string}
     * @memberof InventoryListBean
     */
    outWarehouseId?: string;
    /**
     * 
     * @type {number}
     * @memberof InventoryListBean
     */
    inventoryType?: number;
    /**
     * 
     * @type {string}
     * @memberof InventoryListBean
     */
    inventoryTypeDesc?: string;
    /**
     * 
     * @type {number}
     * @memberof InventoryListBean
     */
    count?: number;
}

export function InventoryListBeanFromJSON(json: any): InventoryListBean {
    return InventoryListBeanFromJSONTyped(json, false);
}

export function InventoryListBeanFromJSONTyped(json: any, ignoreDiscriminator: boolean): InventoryListBean {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'warehouseId': !exists(json, 'warehouse_id') ? undefined : json['warehouse_id'],
        'outWarehouseId': !exists(json, 'out_warehouse_id') ? undefined : json['out_warehouse_id'],
        'inventoryType': !exists(json, 'inventory_type') ? undefined : json['inventory_type'],
        'inventoryTypeDesc': !exists(json, 'inventory_type_desc') ? undefined : json['inventory_type_desc'],
        'count': !exists(json, 'count') ? undefined : json['count'],
    };
}

export function InventoryListBeanToJSON(value?: InventoryListBean | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'warehouse_id': value.warehouseId,
        'out_warehouse_id': value.outWarehouseId,
        'inventory_type': value.inventoryType,
        'inventory_type_desc': value.inventoryTypeDesc,
        'count': value.count,
    };
}


