/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    ProductInfoBean,
    ProductInfoBeanFromJSON,
    ProductInfoBeanFromJSONTyped,
    ProductInfoBeanToJSON,
} from './';

/**
 * 
 * @export
 * @interface LogisticsInfoBean
 */
export interface LogisticsInfoBean {
    /**
     * 
     * @type {string}
     * @memberof LogisticsInfoBean
     */
    trackingNo?: string;
    /**
     * 
     * @type {string}
     * @memberof LogisticsInfoBean
     */
    company?: string;
    /**
     * 
     * @type {number}
     * @memberof LogisticsInfoBean
     */
    shipTime?: number;
    /**
     * 
     * @type {string}
     * @memberof LogisticsInfoBean
     */
    deliveryId?: string;
    /**
     * 
     * @type {string}
     * @memberof LogisticsInfoBean
     */
    companyName?: string;
    /**
     * 
     * @type {Array<ProductInfoBean>}
     * @memberof LogisticsInfoBean
     */
    productInfo?: Array<ProductInfoBean>;
}

export function LogisticsInfoBeanFromJSON(json: any): LogisticsInfoBean {
    return LogisticsInfoBeanFromJSONTyped(json, false);
}

export function LogisticsInfoBeanFromJSONTyped(json: any, ignoreDiscriminator: boolean): LogisticsInfoBean {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'trackingNo': !exists(json, 'tracking_no') ? undefined : json['tracking_no'],
        'company': !exists(json, 'company') ? undefined : json['company'],
        'shipTime': !exists(json, 'ship_time') ? undefined : json['ship_time'],
        'deliveryId': !exists(json, 'delivery_id') ? undefined : json['delivery_id'],
        'companyName': !exists(json, 'company_name') ? undefined : json['company_name'],
        'productInfo': !exists(json, 'product_info') ? undefined : ((json['product_info'] as Array<any>).map(ProductInfoBeanFromJSON)),
    };
}

export function LogisticsInfoBeanToJSON(value?: LogisticsInfoBean | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'tracking_no': value.trackingNo,
        'company': value.company,
        'ship_time': value.shipTime,
        'delivery_id': value.deliveryId,
        'company_name': value.companyName,
        'product_info': value.productInfo === undefined ? undefined : ((value.productInfo as Array<any>).map(ProductInfoBeanToJSON)),
    };
}


