/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface OrderPhaseListBean
 */
export interface OrderPhaseListBean {
    /**
     * 
     * @type {string}
     * @memberof OrderPhaseListBean
     */
    phaseOrderId?: string;
    /**
     * 
     * @type {number}
     * @memberof OrderPhaseListBean
     */
    totalPhase?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderPhaseListBean
     */
    currentPhase?: number;
    /**
     * 
     * @type {boolean}
     * @memberof OrderPhaseListBean
     */
    paySuccess?: boolean;
    /**
     * 
     * @type {string}
     * @memberof OrderPhaseListBean
     */
    skuOrderId?: string;
    /**
     * 
     * @type {number}
     * @memberof OrderPhaseListBean
     */
    campaignId?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderPhaseListBean
     */
    phasePayablePrice?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderPhaseListBean
     */
    phasePayType?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderPhaseListBean
     */
    phaseOpenTime?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderPhaseListBean
     */
    phasePayTime?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderPhaseListBean
     */
    phaseCloseTime?: number;
    /**
     * 
     * @type {string}
     * @memberof OrderPhaseListBean
     */
    channelPaymentNo?: string;
    /**
     * 
     * @type {number}
     * @memberof OrderPhaseListBean
     */
    phaseOrderAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderPhaseListBean
     */
    phaseSumAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderPhaseListBean
     */
    phasePostAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderPhaseListBean
     */
    phasePayAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof OrderPhaseListBean
     */
    phasePromotionAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof OrderPhaseListBean
     */
    currentPhaseStatusDesc?: string;
    /**
     * 
     * @type {number}
     * @memberof OrderPhaseListBean
     */
    skuPrice?: number;
}

export function OrderPhaseListBeanFromJSON(json: any): OrderPhaseListBean {
    return OrderPhaseListBeanFromJSONTyped(json, false);
}

export function OrderPhaseListBeanFromJSONTyped(json: any, ignoreDiscriminator: boolean): OrderPhaseListBean {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'phaseOrderId': !exists(json, 'phase_order_id') ? undefined : json['phase_order_id'],
        'totalPhase': !exists(json, 'total_phase') ? undefined : json['total_phase'],
        'currentPhase': !exists(json, 'current_phase') ? undefined : json['current_phase'],
        'paySuccess': !exists(json, 'pay_success') ? undefined : json['pay_success'],
        'skuOrderId': !exists(json, 'sku_order_id') ? undefined : json['sku_order_id'],
        'campaignId': !exists(json, 'campaign_id') ? undefined : json['campaign_id'],
        'phasePayablePrice': !exists(json, 'phase_payable_price') ? undefined : json['phase_payable_price'],
        'phasePayType': !exists(json, 'phase_pay_type') ? undefined : json['phase_pay_type'],
        'phaseOpenTime': !exists(json, 'phase_open_time') ? undefined : json['phase_open_time'],
        'phasePayTime': !exists(json, 'phase_pay_time') ? undefined : json['phase_pay_time'],
        'phaseCloseTime': !exists(json, 'phase_close_time') ? undefined : json['phase_close_time'],
        'channelPaymentNo': !exists(json, 'channel_payment_no') ? undefined : json['channel_payment_no'],
        'phaseOrderAmount': !exists(json, 'phase_order_amount') ? undefined : json['phase_order_amount'],
        'phaseSumAmount': !exists(json, 'phase_sum_amount') ? undefined : json['phase_sum_amount'],
        'phasePostAmount': !exists(json, 'phase_post_amount') ? undefined : json['phase_post_amount'],
        'phasePayAmount': !exists(json, 'phase_pay_amount') ? undefined : json['phase_pay_amount'],
        'phasePromotionAmount': !exists(json, 'phase_promotion_amount') ? undefined : json['phase_promotion_amount'],
        'currentPhaseStatusDesc': !exists(json, 'current_phase_status_desc') ? undefined : json['current_phase_status_desc'],
        'skuPrice': !exists(json, 'sku_price') ? undefined : json['sku_price'],
    };
}

export function OrderPhaseListBeanToJSON(value?: OrderPhaseListBean | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'phase_order_id': value.phaseOrderId,
        'total_phase': value.totalPhase,
        'current_phase': value.currentPhase,
        'pay_success': value.paySuccess,
        'sku_order_id': value.skuOrderId,
        'campaign_id': value.campaignId,
        'phase_payable_price': value.phasePayablePrice,
        'phase_pay_type': value.phasePayType,
        'phase_open_time': value.phaseOpenTime,
        'phase_pay_time': value.phasePayTime,
        'phase_close_time': value.phaseCloseTime,
        'channel_payment_no': value.channelPaymentNo,
        'phase_order_amount': value.phaseOrderAmount,
        'phase_sum_amount': value.phaseSumAmount,
        'phase_post_amount': value.phasePostAmount,
        'phase_pay_amount': value.phasePayAmount,
        'phase_promotion_amount': value.phasePromotionAmount,
        'current_phase_status_desc': value.currentPhaseStatusDesc,
        'sku_price': value.skuPrice,
    };
}


