/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    SkuSpecsBean,
    SkuSpecsBeanFromJSON,
    SkuSpecsBeanFromJSONTyped,
    SkuSpecsBeanToJSON,
} from './';

/**
 * 
 * @export
 * @interface ProductInfoBean
 */
export interface ProductInfoBean {
    /**
     * 
     * @type {string}
     * @memberof ProductInfoBean
     */
    productName?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductInfoBean
     */
    price?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductInfoBean
     */
    outerSkuId?: string;
    /**
     * 
     * @type {number}
     * @memberof ProductInfoBean
     */
    skuId?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductInfoBean
     */
    productCount?: number;
    /**
     * 
     * @type {number}
     * @memberof ProductInfoBean
     */
    productId?: number;
    /**
     * 
     * @type {string}
     * @memberof ProductInfoBean
     */
    skuOrderId?: string;
    /**
     * 
     * @type {Array<SkuSpecsBean>}
     * @memberof ProductInfoBean
     */
    skuSpecs?: Array<SkuSpecsBean>;
}

export function ProductInfoBeanFromJSON(json: any): ProductInfoBean {
    return ProductInfoBeanFromJSONTyped(json, false);
}

export function ProductInfoBeanFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProductInfoBean {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'productName': !exists(json, 'product_name') ? undefined : json['product_name'],
        'price': !exists(json, 'price') ? undefined : json['price'],
        'outerSkuId': !exists(json, 'outer_sku_id') ? undefined : json['outer_sku_id'],
        'skuId': !exists(json, 'sku_id') ? undefined : json['sku_id'],
        'productCount': !exists(json, 'product_count') ? undefined : json['product_count'],
        'productId': !exists(json, 'product_id') ? undefined : json['product_id'],
        'skuOrderId': !exists(json, 'sku_order_id') ? undefined : json['sku_order_id'],
        'skuSpecs': !exists(json, 'sku_specs') ? undefined : ((json['sku_specs'] as Array<any>).map(SkuSpecsBeanFromJSON)),
    };
}

export function ProductInfoBeanToJSON(value?: ProductInfoBean | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'product_name': value.productName,
        'price': value.price,
        'outer_sku_id': value.outerSkuId,
        'sku_id': value.skuId,
        'product_count': value.productCount,
        'product_id': value.productId,
        'sku_order_id': value.skuOrderId,
        'sku_specs': value.skuSpecs === undefined ? undefined : ((value.skuSpecs as Array<any>).map(SkuSpecsBeanToJSON)),
    };
}


