/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AfterSaleInfoBean,
    AfterSaleInfoBeanFromJSON,
    AfterSaleInfoBeanFromJSONTyped,
    AfterSaleInfoBeanToJSON,
    InventoryListBean,
    InventoryListBeanFromJSON,
    InventoryListBeanFromJSONTyped,
    InventoryListBeanToJSON,
    PostAddrBean,
    PostAddrBeanFromJSON,
    PostAddrBeanFromJSONTyped,
    PostAddrBeanToJSON,
    SpecBean,
    SpecBeanFromJSON,
    SpecBeanFromJSONTyped,
    SpecBeanToJSON,
} from './';

/**
 * 
 * @export
 * @interface SkuOrderListBean
 */
export interface SkuOrderListBean {
    /**
     * 
     * @type {string}
     * @memberof SkuOrderListBean
     */
    orderId?: string;
    /**
     * 
     * @type {string}
     * @memberof SkuOrderListBean
     */
    parentOrderId?: string;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    orderLevel?: number;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    biz?: number;
    /**
     * 
     * @type {string}
     * @memberof SkuOrderListBean
     */
    bizDesc?: string;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    orderType?: number;
    /**
     * 
     * @type {string}
     * @memberof SkuOrderListBean
     */
    orderTypeDesc?: string;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    tradeType?: number;
    /**
     * 
     * @type {string}
     * @memberof SkuOrderListBean
     */
    tradeTypeDesc?: string;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    orderStatus?: number;
    /**
     * 
     * @type {string}
     * @memberof SkuOrderListBean
     */
    orderStatusDesc?: string;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    mainStatus?: number;
    /**
     * 
     * @type {string}
     * @memberof SkuOrderListBean
     */
    mainStatusDesc?: string;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    payTime?: number;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    orderExpireTime?: number;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    finishTime?: number;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    createTime?: number;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    updateTime?: number;
    /**
     * 
     * @type {string}
     * @memberof SkuOrderListBean
     */
    cancelReason?: string;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    bType?: number;
    /**
     * 
     * @type {string}
     * @memberof SkuOrderListBean
     */
    bTypeDesc?: string;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    subBType?: number;
    /**
     * 
     * @type {string}
     * @memberof SkuOrderListBean
     */
    subBTypeDesc?: string;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    sendPay?: number;
    /**
     * 
     * @type {string}
     * @memberof SkuOrderListBean
     */
    sendPayDesc?: string;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    authorId?: number;
    /**
     * 
     * @type {string}
     * @memberof SkuOrderListBean
     */
    authorName?: string;
    /**
     * 
     * @type {string}
     * @memberof SkuOrderListBean
     */
    themeType?: string;
    /**
     * 
     * @type {string}
     * @memberof SkuOrderListBean
     */
    themeTypeDesc?: string;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    appId?: number;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    roomId?: number;
    /**
     * 
     * @type {string}
     * @memberof SkuOrderListBean
     */
    contentId?: string;
    /**
     * 
     * @type {string}
     * @memberof SkuOrderListBean
     */
    videoId?: string;
    /**
     * 
     * @type {string}
     * @memberof SkuOrderListBean
     */
    originId?: string;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    cid?: number;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    cBiz?: number;
    /**
     * 
     * @type {string}
     * @memberof SkuOrderListBean
     */
    cBizDesc?: string;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    pageId?: number;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    payType?: number;
    /**
     * 
     * @type {string}
     * @memberof SkuOrderListBean
     */
    channelPaymentNo?: string;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    orderAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    payAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    postInsuranceAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    modifyAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    modifyPostAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    promotionAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    promotionShopAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    promotionPlatformAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    shopCostAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    platformCostAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    promotionTalentAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    promotionPayAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof SkuOrderListBean
     */
    code?: string;
    /**
     * 
     * @type {string}
     * @memberof SkuOrderListBean
     */
    postTel?: string;
    /**
     * 
     * @type {string}
     * @memberof SkuOrderListBean
     */
    postReceiver?: string;
    /**
     * 
     * @type {PostAddrBean}
     * @memberof SkuOrderListBean
     */
    postAddr?: PostAddrBean;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    expShipTime?: number;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    shipTime?: number;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    logisticsReceiptTime?: number;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    confirmReceiptTime?: number;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    goodsType?: number;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    productId?: number;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    skuId?: number;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    firstCid?: number;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    secondCid?: number;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    thirdCid?: number;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    fourthCid?: number;
    /**
     * 
     * @type {string}
     * @memberof SkuOrderListBean
     */
    outSkuId?: string;
    /**
     * 
     * @type {string}
     * @memberof SkuOrderListBean
     */
    supplierId?: string;
    /**
     * 
     * @type {string}
     * @memberof SkuOrderListBean
     */
    outProductId?: string;
    /**
     * 
     * @type {string}
     * @memberof SkuOrderListBean
     */
    inventoryType?: string;
    /**
     * 
     * @type {string}
     * @memberof SkuOrderListBean
     */
    inventoryTypeDesc?: string;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    reduceStockType?: number;
    /**
     * 
     * @type {string}
     * @memberof SkuOrderListBean
     */
    reduceStockTypeDesc?: string;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    originAmount?: number;
    /**
     * 
     * @type {boolean}
     * @memberof SkuOrderListBean
     */
    hasTax?: boolean;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    itemNum?: number;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    sumAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof SkuOrderListBean
     */
    sourcePlatform?: string;
    /**
     * 
     * @type {string}
     * @memberof SkuOrderListBean
     */
    productPic?: string;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    isComment?: number;
    /**
     * 
     * @type {string}
     * @memberof SkuOrderListBean
     */
    productName?: string;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    postAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof SkuOrderListBean
     */
    preSaleType?: number;
    /**
     * 
     * @type {AfterSaleInfoBean}
     * @memberof SkuOrderListBean
     */
    afterSaleInfo?: AfterSaleInfoBean;
    /**
     * 
     * @type {Array<SpecBean>}
     * @memberof SkuOrderListBean
     */
    spec?: Array<SpecBean>;
    /**
     * 
     * @type {Array<string>}
     * @memberof SkuOrderListBean
     */
    warehouseIds?: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof SkuOrderListBean
     */
    outWarehouseIds?: Array<string>;
    /**
     * 
     * @type {Array<InventoryListBean>}
     * @memberof SkuOrderListBean
     */
    inventoryList?: Array<InventoryListBean>;
}

export function SkuOrderListBeanFromJSON(json: any): SkuOrderListBean {
    return SkuOrderListBeanFromJSONTyped(json, false);
}

export function SkuOrderListBeanFromJSONTyped(json: any, ignoreDiscriminator: boolean): SkuOrderListBean {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'orderId': !exists(json, 'order_id') ? undefined : json['order_id'],
        'parentOrderId': !exists(json, 'parent_order_id') ? undefined : json['parent_order_id'],
        'orderLevel': !exists(json, 'order_level') ? undefined : json['order_level'],
        'biz': !exists(json, 'biz') ? undefined : json['biz'],
        'bizDesc': !exists(json, 'biz_desc') ? undefined : json['biz_desc'],
        'orderType': !exists(json, 'order_type') ? undefined : json['order_type'],
        'orderTypeDesc': !exists(json, 'order_type_desc') ? undefined : json['order_type_desc'],
        'tradeType': !exists(json, 'trade_type') ? undefined : json['trade_type'],
        'tradeTypeDesc': !exists(json, 'trade_type_desc') ? undefined : json['trade_type_desc'],
        'orderStatus': !exists(json, 'order_status') ? undefined : json['order_status'],
        'orderStatusDesc': !exists(json, 'order_status_desc') ? undefined : json['order_status_desc'],
        'mainStatus': !exists(json, 'main_status') ? undefined : json['main_status'],
        'mainStatusDesc': !exists(json, 'main_status_desc') ? undefined : json['main_status_desc'],
        'payTime': !exists(json, 'pay_time') ? undefined : json['pay_time'],
        'orderExpireTime': !exists(json, 'order_expire_time') ? undefined : json['order_expire_time'],
        'finishTime': !exists(json, 'finish_time') ? undefined : json['finish_time'],
        'createTime': !exists(json, 'create_time') ? undefined : json['create_time'],
        'updateTime': !exists(json, 'update_time') ? undefined : json['update_time'],
        'cancelReason': !exists(json, 'cancel_reason') ? undefined : json['cancel_reason'],
        'bType': !exists(json, 'b_type') ? undefined : json['b_type'],
        'bTypeDesc': !exists(json, 'b_type_desc') ? undefined : json['b_type_desc'],
        'subBType': !exists(json, 'sub_b_type') ? undefined : json['sub_b_type'],
        'subBTypeDesc': !exists(json, 'sub_b_type_desc') ? undefined : json['sub_b_type_desc'],
        'sendPay': !exists(json, 'send_pay') ? undefined : json['send_pay'],
        'sendPayDesc': !exists(json, 'send_pay_desc') ? undefined : json['send_pay_desc'],
        'authorId': !exists(json, 'author_id') ? undefined : json['author_id'],
        'authorName': !exists(json, 'author_name') ? undefined : json['author_name'],
        'themeType': !exists(json, 'theme_type') ? undefined : json['theme_type'],
        'themeTypeDesc': !exists(json, 'theme_type_desc') ? undefined : json['theme_type_desc'],
        'appId': !exists(json, 'app_id') ? undefined : json['app_id'],
        'roomId': !exists(json, 'room_id') ? undefined : json['room_id'],
        'contentId': !exists(json, 'content_id') ? undefined : json['content_id'],
        'videoId': !exists(json, 'video_id') ? undefined : json['video_id'],
        'originId': !exists(json, 'origin_id') ? undefined : json['origin_id'],
        'cid': !exists(json, 'cid') ? undefined : json['cid'],
        'cBiz': !exists(json, 'c_biz') ? undefined : json['c_biz'],
        'cBizDesc': !exists(json, 'c_biz_desc') ? undefined : json['c_biz_desc'],
        'pageId': !exists(json, 'page_id') ? undefined : json['page_id'],
        'payType': !exists(json, 'pay_type') ? undefined : json['pay_type'],
        'channelPaymentNo': !exists(json, 'channel_payment_no') ? undefined : json['channel_payment_no'],
        'orderAmount': !exists(json, 'order_amount') ? undefined : json['order_amount'],
        'payAmount': !exists(json, 'pay_amount') ? undefined : json['pay_amount'],
        'postInsuranceAmount': !exists(json, 'post_insurance_amount') ? undefined : json['post_insurance_amount'],
        'modifyAmount': !exists(json, 'modify_amount') ? undefined : json['modify_amount'],
        'modifyPostAmount': !exists(json, 'modify_post_amount') ? undefined : json['modify_post_amount'],
        'promotionAmount': !exists(json, 'promotion_amount') ? undefined : json['promotion_amount'],
        'promotionShopAmount': !exists(json, 'promotion_shop_amount') ? undefined : json['promotion_shop_amount'],
        'promotionPlatformAmount': !exists(json, 'promotion_platform_amount') ? undefined : json['promotion_platform_amount'],
        'shopCostAmount': !exists(json, 'shop_cost_amount') ? undefined : json['shop_cost_amount'],
        'platformCostAmount': !exists(json, 'platform_cost_amount') ? undefined : json['platform_cost_amount'],
        'promotionTalentAmount': !exists(json, 'promotion_talent_amount') ? undefined : json['promotion_talent_amount'],
        'promotionPayAmount': !exists(json, 'promotion_pay_amount') ? undefined : json['promotion_pay_amount'],
        'code': !exists(json, 'code') ? undefined : json['code'],
        'postTel': !exists(json, 'post_tel') ? undefined : json['post_tel'],
        'postReceiver': !exists(json, 'post_receiver') ? undefined : json['post_receiver'],
        'postAddr': !exists(json, 'post_addr') ? undefined : PostAddrBeanFromJSON(json['post_addr']),
        'expShipTime': !exists(json, 'exp_ship_time') ? undefined : json['exp_ship_time'],
        'shipTime': !exists(json, 'ship_time') ? undefined : json['ship_time'],
        'logisticsReceiptTime': !exists(json, 'logistics_receipt_time') ? undefined : json['logistics_receipt_time'],
        'confirmReceiptTime': !exists(json, 'confirm_receipt_time') ? undefined : json['confirm_receipt_time'],
        'goodsType': !exists(json, 'goods_type') ? undefined : json['goods_type'],
        'productId': !exists(json, 'product_id') ? undefined : json['product_id'],
        'skuId': !exists(json, 'sku_id') ? undefined : json['sku_id'],
        'firstCid': !exists(json, 'first_cid') ? undefined : json['first_cid'],
        'secondCid': !exists(json, 'second_cid') ? undefined : json['second_cid'],
        'thirdCid': !exists(json, 'third_cid') ? undefined : json['third_cid'],
        'fourthCid': !exists(json, 'fourth_cid') ? undefined : json['fourth_cid'],
        'outSkuId': !exists(json, 'out_sku_id') ? undefined : json['out_sku_id'],
        'supplierId': !exists(json, 'supplier_id') ? undefined : json['supplier_id'],
        'outProductId': !exists(json, 'out_product_id') ? undefined : json['out_product_id'],
        'inventoryType': !exists(json, 'inventory_type') ? undefined : json['inventory_type'],
        'inventoryTypeDesc': !exists(json, 'inventory_type_desc') ? undefined : json['inventory_type_desc'],
        'reduceStockType': !exists(json, 'reduce_stock_type') ? undefined : json['reduce_stock_type'],
        'reduceStockTypeDesc': !exists(json, 'reduce_stock_type_desc') ? undefined : json['reduce_stock_type_desc'],
        'originAmount': !exists(json, 'origin_amount') ? undefined : json['origin_amount'],
        'hasTax': !exists(json, 'has_tax') ? undefined : json['has_tax'],
        'itemNum': !exists(json, 'item_num') ? undefined : json['item_num'],
        'sumAmount': !exists(json, 'sum_amount') ? undefined : json['sum_amount'],
        'sourcePlatform': !exists(json, 'source_platform') ? undefined : json['source_platform'],
        'productPic': !exists(json, 'product_pic') ? undefined : json['product_pic'],
        'isComment': !exists(json, 'is_comment') ? undefined : json['is_comment'],
        'productName': !exists(json, 'product_name') ? undefined : json['product_name'],
        'postAmount': !exists(json, 'post_amount') ? undefined : json['post_amount'],
        'preSaleType': !exists(json, 'pre_sale_type') ? undefined : json['pre_sale_type'],
        'afterSaleInfo': !exists(json, 'after_sale_info') ? undefined : AfterSaleInfoBeanFromJSON(json['after_sale_info']),
        'spec': !exists(json, 'spec') ? undefined : ((json['spec'] as Array<any>).map(SpecBeanFromJSON)),
        'warehouseIds': !exists(json, 'warehouse_ids') ? undefined : json['warehouse_ids'],
        'outWarehouseIds': !exists(json, 'out_warehouse_ids') ? undefined : json['out_warehouse_ids'],
        'inventoryList': !exists(json, 'inventory_list') ? undefined : ((json['inventory_list'] as Array<any>).map(InventoryListBeanFromJSON)),
    };
}

export function SkuOrderListBeanToJSON(value?: SkuOrderListBean | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'order_id': value.orderId,
        'parent_order_id': value.parentOrderId,
        'order_level': value.orderLevel,
        'biz': value.biz,
        'biz_desc': value.bizDesc,
        'order_type': value.orderType,
        'order_type_desc': value.orderTypeDesc,
        'trade_type': value.tradeType,
        'trade_type_desc': value.tradeTypeDesc,
        'order_status': value.orderStatus,
        'order_status_desc': value.orderStatusDesc,
        'main_status': value.mainStatus,
        'main_status_desc': value.mainStatusDesc,
        'pay_time': value.payTime,
        'order_expire_time': value.orderExpireTime,
        'finish_time': value.finishTime,
        'create_time': value.createTime,
        'update_time': value.updateTime,
        'cancel_reason': value.cancelReason,
        'b_type': value.bType,
        'b_type_desc': value.bTypeDesc,
        'sub_b_type': value.subBType,
        'sub_b_type_desc': value.subBTypeDesc,
        'send_pay': value.sendPay,
        'send_pay_desc': value.sendPayDesc,
        'author_id': value.authorId,
        'author_name': value.authorName,
        'theme_type': value.themeType,
        'theme_type_desc': value.themeTypeDesc,
        'app_id': value.appId,
        'room_id': value.roomId,
        'content_id': value.contentId,
        'video_id': value.videoId,
        'origin_id': value.originId,
        'cid': value.cid,
        'c_biz': value.cBiz,
        'c_biz_desc': value.cBizDesc,
        'page_id': value.pageId,
        'pay_type': value.payType,
        'channel_payment_no': value.channelPaymentNo,
        'order_amount': value.orderAmount,
        'pay_amount': value.payAmount,
        'post_insurance_amount': value.postInsuranceAmount,
        'modify_amount': value.modifyAmount,
        'modify_post_amount': value.modifyPostAmount,
        'promotion_amount': value.promotionAmount,
        'promotion_shop_amount': value.promotionShopAmount,
        'promotion_platform_amount': value.promotionPlatformAmount,
        'shop_cost_amount': value.shopCostAmount,
        'platform_cost_amount': value.platformCostAmount,
        'promotion_talent_amount': value.promotionTalentAmount,
        'promotion_pay_amount': value.promotionPayAmount,
        'code': value.code,
        'post_tel': value.postTel,
        'post_receiver': value.postReceiver,
        'post_addr': PostAddrBeanToJSON(value.postAddr),
        'exp_ship_time': value.expShipTime,
        'ship_time': value.shipTime,
        'logistics_receipt_time': value.logisticsReceiptTime,
        'confirm_receipt_time': value.confirmReceiptTime,
        'goods_type': value.goodsType,
        'product_id': value.productId,
        'sku_id': value.skuId,
        'first_cid': value.firstCid,
        'second_cid': value.secondCid,
        'third_cid': value.thirdCid,
        'fourth_cid': value.fourthCid,
        'out_sku_id': value.outSkuId,
        'supplier_id': value.supplierId,
        'out_product_id': value.outProductId,
        'inventory_type': value.inventoryType,
        'inventory_type_desc': value.inventoryTypeDesc,
        'reduce_stock_type': value.reduceStockType,
        'reduce_stock_type_desc': value.reduceStockTypeDesc,
        'origin_amount': value.originAmount,
        'has_tax': value.hasTax,
        'item_num': value.itemNum,
        'sum_amount': value.sumAmount,
        'source_platform': value.sourcePlatform,
        'product_pic': value.productPic,
        'is_comment': value.isComment,
        'product_name': value.productName,
        'post_amount': value.postAmount,
        'pre_sale_type': value.preSaleType,
        'after_sale_info': AfterSaleInfoBeanToJSON(value.afterSaleInfo),
        'spec': value.spec === undefined ? undefined : ((value.spec as Array<any>).map(SpecBeanToJSON)),
        'warehouse_ids': value.warehouseIds,
        'out_warehouse_ids': value.outWarehouseIds,
        'inventory_list': value.inventoryList === undefined ? undefined : ((value.inventoryList as Array<any>).map(InventoryListBeanToJSON)),
    };
}


