/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SkuSpecsBean
 */
export interface SkuSpecsBean {
    /**
     * 
     * @type {string}
     * @memberof SkuSpecsBean
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof SkuSpecsBean
     */
    value?: string;
}

export function SkuSpecsBeanFromJSON(json: any): SkuSpecsBean {
    return SkuSpecsBeanFromJSONTyped(json, false);
}

export function SkuSpecsBeanFromJSONTyped(json: any, ignoreDiscriminator: boolean): SkuSpecsBean {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': !exists(json, 'name') ? undefined : json['name'],
        'value': !exists(json, 'value') ? undefined : json['value'],
    };
}

export function SkuSpecsBeanToJSON(value?: SkuSpecsBean | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'value': value.value,
    };
}


