/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    LogisticsInfoBean,
    LogisticsInfoBeanFromJSON,
    LogisticsInfoBeanFromJSONTyped,
    LogisticsInfoBeanToJSON,
    OrderPhaseListBean,
    OrderPhaseListBeanFromJSON,
    OrderPhaseListBeanFromJSONTyped,
    OrderPhaseListBeanToJSON,
    PostAddrBean,
    PostAddrBeanFromJSON,
    PostAddrBeanFromJSONTyped,
    PostAddrBeanToJSON,
    SkuOrderListBean,
    SkuOrderListBeanFromJSON,
    SkuOrderListBeanFromJSONTyped,
    SkuOrderListBeanToJSON,
} from './';

/**
 * 
 * @export
 * @interface Trade
 */
export interface Trade {
    /**
     * 
     * @type {number}
     * @memberof Trade
     */
    shopId?: number;
    /**
     * 
     * @type {string}
     * @memberof Trade
     */
    shopName?: string;
    /**
     * 
     * @type {string}
     * @memberof Trade
     */
    openId?: string;
    /**
     * 
     * @type {string}
     * @memberof Trade
     */
    orderId?: string;
    /**
     * 
     * @type {number}
     * @memberof Trade
     */
    orderLevel?: number;
    /**
     * 
     * @type {number}
     * @memberof Trade
     */
    biz?: number;
    /**
     * 
     * @type {string}
     * @memberof Trade
     */
    bizDesc?: string;
    /**
     * 
     * @type {number}
     * @memberof Trade
     */
    orderType?: number;
    /**
     * 
     * @type {string}
     * @memberof Trade
     */
    orderTypeDesc?: string;
    /**
     * 
     * @type {number}
     * @memberof Trade
     */
    tradeType?: number;
    /**
     * 
     * @type {string}
     * @memberof Trade
     */
    tradeTypeDesc?: string;
    /**
     * 
     * @type {number}
     * @memberof Trade
     */
    orderStatus?: number;
    /**
     * 
     * @type {string}
     * @memberof Trade
     */
    orderStatusDesc?: string;
    /**
     * 
     * @type {number}
     * @memberof Trade
     */
    mainStatus?: number;
    /**
     * 
     * @type {string}
     * @memberof Trade
     */
    mainStatusDesc?: string;
    /**
     * 
     * @type {number}
     * @memberof Trade
     */
    payTime?: number;
    /**
     * 
     * @type {number}
     * @memberof Trade
     */
    orderExpireTime?: number;
    /**
     * 
     * @type {number}
     * @memberof Trade
     */
    finishTime?: number;
    /**
     * 
     * @type {number}
     * @memberof Trade
     */
    createTime?: number;
    /**
     * 
     * @type {number}
     * @memberof Trade
     */
    updateTime?: number;
    /**
     * 
     * @type {string}
     * @memberof Trade
     */
    cancelReason?: string;
    /**
     * 
     * @type {string}
     * @memberof Trade
     */
    buyerWords?: string;
    /**
     * 
     * @type {string}
     * @memberof Trade
     */
    sellerWords?: string;
    /**
     * 
     * @type {number}
     * @memberof Trade
     */
    bType?: number;
    /**
     * 
     * @type {string}
     * @memberof Trade
     */
    bTypeDesc?: string;
    /**
     * 
     * @type {number}
     * @memberof Trade
     */
    subBType?: number;
    /**
     * 
     * @type {string}
     * @memberof Trade
     */
    subBTypeDesc?: string;
    /**
     * 
     * @type {number}
     * @memberof Trade
     */
    appId?: number;
    /**
     * 
     * @type {number}
     * @memberof Trade
     */
    payType?: number;
    /**
     * 
     * @type {string}
     * @memberof Trade
     */
    channelPaymentNo?: string;
    /**
     * 
     * @type {number}
     * @memberof Trade
     */
    orderAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof Trade
     */
    payAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof Trade
     */
    postAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof Trade
     */
    postInsuranceAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof Trade
     */
    modifyAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof Trade
     */
    modifyPostAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof Trade
     */
    promotionAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof Trade
     */
    promotionShopAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof Trade
     */
    promotionPlatformAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof Trade
     */
    shopCostAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof Trade
     */
    platformCostAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof Trade
     */
    promotionTalentAmount?: number;
    /**
     * 
     * @type {number}
     * @memberof Trade
     */
    promotionPayAmount?: number;
    /**
     * 
     * @type {string}
     * @memberof Trade
     */
    postTel?: string;
    /**
     * 
     * @type {string}
     * @memberof Trade
     */
    postReceiver?: string;
    /**
     * 
     * @type {PostAddrBean}
     * @memberof Trade
     */
    postAddr?: PostAddrBean;
    /**
     * 
     * @type {number}
     * @memberof Trade
     */
    expShipTime?: number;
    /**
     * 
     * @type {number}
     * @memberof Trade
     */
    shipTime?: number;
    /**
     * 
     * @type {number}
     * @memberof Trade
     */
    sellerRemarkStars?: number;
    /**
     * 
     * @type {string}
     * @memberof Trade
     */
    doudianOpenId?: string;
    /**
     * 
     * @type {Array<LogisticsInfoBean>}
     * @memberof Trade
     */
    logisticsInfo?: Array<LogisticsInfoBean>;
    /**
     * 
     * @type {Array<SkuOrderListBean>}
     * @memberof Trade
     */
    skuOrderList?: Array<SkuOrderListBean>;
    /**
     * 
     * @type {Array<OrderPhaseListBean>}
     * @memberof Trade
     */
    orderPhaseList?: Array<OrderPhaseListBean>;
}

export function TradeFromJSON(json: any): Trade {
    return TradeFromJSONTyped(json, false);
}

export function TradeFromJSONTyped(json: any, ignoreDiscriminator: boolean): Trade {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'shopId': !exists(json, 'shop_id') ? undefined : json['shop_id'],
        'shopName': !exists(json, 'shop_name') ? undefined : json['shop_name'],
        'openId': !exists(json, 'open_id') ? undefined : json['open_id'],
        'orderId': !exists(json, 'order_id') ? undefined : json['order_id'],
        'orderLevel': !exists(json, 'order_level') ? undefined : json['order_level'],
        'biz': !exists(json, 'biz') ? undefined : json['biz'],
        'bizDesc': !exists(json, 'biz_desc') ? undefined : json['biz_desc'],
        'orderType': !exists(json, 'order_type') ? undefined : json['order_type'],
        'orderTypeDesc': !exists(json, 'order_type_desc') ? undefined : json['order_type_desc'],
        'tradeType': !exists(json, 'trade_type') ? undefined : json['trade_type'],
        'tradeTypeDesc': !exists(json, 'trade_type_desc') ? undefined : json['trade_type_desc'],
        'orderStatus': !exists(json, 'order_status') ? undefined : json['order_status'],
        'orderStatusDesc': !exists(json, 'order_status_desc') ? undefined : json['order_status_desc'],
        'mainStatus': !exists(json, 'main_status') ? undefined : json['main_status'],
        'mainStatusDesc': !exists(json, 'main_status_desc') ? undefined : json['main_status_desc'],
        'payTime': !exists(json, 'pay_time') ? undefined : json['pay_time'],
        'orderExpireTime': !exists(json, 'order_expire_time') ? undefined : json['order_expire_time'],
        'finishTime': !exists(json, 'finish_time') ? undefined : json['finish_time'],
        'createTime': !exists(json, 'create_time') ? undefined : json['create_time'],
        'updateTime': !exists(json, 'update_time') ? undefined : json['update_time'],
        'cancelReason': !exists(json, 'cancel_reason') ? undefined : json['cancel_reason'],
        'buyerWords': !exists(json, 'buyer_words') ? undefined : json['buyer_words'],
        'sellerWords': !exists(json, 'seller_words') ? undefined : json['seller_words'],
        'bType': !exists(json, 'b_type') ? undefined : json['b_type'],
        'bTypeDesc': !exists(json, 'b_type_desc') ? undefined : json['b_type_desc'],
        'subBType': !exists(json, 'sub_b_type') ? undefined : json['sub_b_type'],
        'subBTypeDesc': !exists(json, 'sub_b_type_desc') ? undefined : json['sub_b_type_desc'],
        'appId': !exists(json, 'app_id') ? undefined : json['app_id'],
        'payType': !exists(json, 'pay_type') ? undefined : json['pay_type'],
        'channelPaymentNo': !exists(json, 'channel_payment_no') ? undefined : json['channel_payment_no'],
        'orderAmount': !exists(json, 'order_amount') ? undefined : json['order_amount'],
        'payAmount': !exists(json, 'pay_amount') ? undefined : json['pay_amount'],
        'postAmount': !exists(json, 'post_amount') ? undefined : json['post_amount'],
        'postInsuranceAmount': !exists(json, 'post_insurance_amount') ? undefined : json['post_insurance_amount'],
        'modifyAmount': !exists(json, 'modify_amount') ? undefined : json['modify_amount'],
        'modifyPostAmount': !exists(json, 'modify_post_amount') ? undefined : json['modify_post_amount'],
        'promotionAmount': !exists(json, 'promotion_amount') ? undefined : json['promotion_amount'],
        'promotionShopAmount': !exists(json, 'promotion_shop_amount') ? undefined : json['promotion_shop_amount'],
        'promotionPlatformAmount': !exists(json, 'promotion_platform_amount') ? undefined : json['promotion_platform_amount'],
        'shopCostAmount': !exists(json, 'shop_cost_amount') ? undefined : json['shop_cost_amount'],
        'platformCostAmount': !exists(json, 'platform_cost_amount') ? undefined : json['platform_cost_amount'],
        'promotionTalentAmount': !exists(json, 'promotion_talent_amount') ? undefined : json['promotion_talent_amount'],
        'promotionPayAmount': !exists(json, 'promotion_pay_amount') ? undefined : json['promotion_pay_amount'],
        'postTel': !exists(json, 'post_tel') ? undefined : json['post_tel'],
        'postReceiver': !exists(json, 'post_receiver') ? undefined : json['post_receiver'],
        'postAddr': !exists(json, 'post_addr') ? undefined : PostAddrBeanFromJSON(json['post_addr']),
        'expShipTime': !exists(json, 'exp_ship_time') ? undefined : json['exp_ship_time'],
        'shipTime': !exists(json, 'ship_time') ? undefined : json['ship_time'],
        'sellerRemarkStars': !exists(json, 'seller_remark_stars') ? undefined : json['seller_remark_stars'],
        'doudianOpenId': !exists(json, 'doudian_open_id') ? undefined : json['doudian_open_id'],
        'logisticsInfo': !exists(json, 'logistics_info') ? undefined : ((json['logistics_info'] as Array<any>).map(LogisticsInfoBeanFromJSON)),
        'skuOrderList': !exists(json, 'sku_order_list') ? undefined : ((json['sku_order_list'] as Array<any>).map(SkuOrderListBeanFromJSON)),
        'orderPhaseList': !exists(json, 'order_phase_list') ? undefined : ((json['order_phase_list'] as Array<any>).map(OrderPhaseListBeanFromJSON)),
    };
}

export function TradeToJSON(value?: Trade | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'shop_id': value.shopId,
        'shop_name': value.shopName,
        'open_id': value.openId,
        'order_id': value.orderId,
        'order_level': value.orderLevel,
        'biz': value.biz,
        'biz_desc': value.bizDesc,
        'order_type': value.orderType,
        'order_type_desc': value.orderTypeDesc,
        'trade_type': value.tradeType,
        'trade_type_desc': value.tradeTypeDesc,
        'order_status': value.orderStatus,
        'order_status_desc': value.orderStatusDesc,
        'main_status': value.mainStatus,
        'main_status_desc': value.mainStatusDesc,
        'pay_time': value.payTime,
        'order_expire_time': value.orderExpireTime,
        'finish_time': value.finishTime,
        'create_time': value.createTime,
        'update_time': value.updateTime,
        'cancel_reason': value.cancelReason,
        'buyer_words': value.buyerWords,
        'seller_words': value.sellerWords,
        'b_type': value.bType,
        'b_type_desc': value.bTypeDesc,
        'sub_b_type': value.subBType,
        'sub_b_type_desc': value.subBTypeDesc,
        'app_id': value.appId,
        'pay_type': value.payType,
        'channel_payment_no': value.channelPaymentNo,
        'order_amount': value.orderAmount,
        'pay_amount': value.payAmount,
        'post_amount': value.postAmount,
        'post_insurance_amount': value.postInsuranceAmount,
        'modify_amount': value.modifyAmount,
        'modify_post_amount': value.modifyPostAmount,
        'promotion_amount': value.promotionAmount,
        'promotion_shop_amount': value.promotionShopAmount,
        'promotion_platform_amount': value.promotionPlatformAmount,
        'shop_cost_amount': value.shopCostAmount,
        'platform_cost_amount': value.platformCostAmount,
        'promotion_talent_amount': value.promotionTalentAmount,
        'promotion_pay_amount': value.promotionPayAmount,
        'post_tel': value.postTel,
        'post_receiver': value.postReceiver,
        'post_addr': PostAddrBeanToJSON(value.postAddr),
        'exp_ship_time': value.expShipTime,
        'ship_time': value.shipTime,
        'seller_remark_stars': value.sellerRemarkStars,
        'doudian_open_id': value.doudianOpenId,
        'logistics_info': value.logisticsInfo === undefined ? undefined : ((value.logisticsInfo as Array<any>).map(LogisticsInfoBeanToJSON)),
        'sku_order_list': value.skuOrderList === undefined ? undefined : ((value.skuOrderList as Array<any>).map(SkuOrderListBeanToJSON)),
        'order_phase_list': value.orderPhaseList === undefined ? undefined : ((value.orderPhaseList as Array<any>).map(OrderPhaseListBeanToJSON)),
    };
}


